name = "TDAnalyze"
uuid = "1feb10ce-27b0-4602-8644-47e2eacc7a3e"
authors = ["ArrogantGao <gaoxuanzhao@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
